name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - name: Slack start notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/plantit/master/plantit/front_end/src/assets/logo-favicon.png
          SLACK_MESSAGE: 'Build started'
          SLACK_TITLE: PlantIT CI
          SLACK_USERNAME: plantit
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ~/.ssh/id_rsa # ${{ github.workspace }}/../private.key
      - name: Bootstrap, build, & test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          CYVERSE_USERNAME: ${{ secrets.CYVERSE_USERNAME }}
          CYVERSE_PASSWORD: ${{ secrets.CYVERSE_PASSWORD }}
        run: |
          chmod +x scripts/bootstrap.sh
          bash scripts/bootstrap.sh -n
          docker-compose -f docker-compose.dev.yml exec -T -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN plantit coverage run --source='.' ./manage.py test
          docker-compose -f docker-compose.dev.yml exec -T -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN plantit coveralls
          docker push computationalplantscience/plantit
      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_DIRECTORY: ${{ secrets.SSH_DIRECTORY }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          chmod +x scripts/deploy.sh
          chmod +x scripts/deploy-ssh.sh
          bash scripts/deploy-ssh.sh
      - name: Slack success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/plantit/master/plantit/front_end/src/assets/logo-favicon.png
          SLACK_MESSAGE: 'Build succeeded'
          SLACK_TITLE: PlantIT CI
          SLACK_USERNAME: plantit